### ISSUE TITLE
Form issue with uPrint SE/SE Plus

### ISSUE THREAD

**Issue by Eric-11** [mayrthom/CartridgeWriter_uPrint#3]
Hi,
I have a uPrint SE Plus. When I read the eprom I get the following (see attached too):
```

er 0 0 0 128
Model carrier ID (8 8-bit values)
000000: b3 96 d6 03 d0 14 10 de                           ........

Model carrier in bay 0: 128 bytes at address 0 (128 8-bit values)
000000: a5 e8 d5 38 6a 55 49 dd f2 35 9e d0 00 86 f4 72   ...8jUI..5.....r
000016: 47 2c c8 99 83 f6 fb 99 ab e8 8e 2f b4 ab b7 58   G,........./...X
000032: 83 8c 38 bc c9 25 98 92 a0 a7 5d 17 b8 78 55 10   ..8..%....]..xU.
000048: a0 a7 5d 17 b8 78 55 10 79 bb 90 1b a1 7c 71 22   ..]..xU.y....|q"
000064: bf 52 00 00 00 00 f8 f2 55 aa 55 67 c4 64 5e be   .R......U.Ug.d^.
000080: 32 3b 00 00 00 00 00 00 dd b8 fa 8e b4 db ea 5b   2;.............[
000096: d1 db 9d bd 01 00 00 00 53 54 52 41 54 41 53 59   ........STRATASY
000112: 53 92 86 54 5c bb e6 81 42 4a 71 fc af b6 fd 20   S..T\...BJq.... 
```

And when I select either uPrint or the uPrint SE/SE Plus I get this popup error:

Input not the right Form
Try Again!
Maybe the wrong Device is connected or the wrong Printer Type is
selected
[cw_error.txt](https://github.com/mayrthom/CartridgeWriter_uPrint/files/7401448/cw_error.txt)

Thanks

**Comment by mayrthom** [comment]
Thank you for opening the issue. I think I fixed the bug now. 
Because I don't have any access anymore to a real stratasys printer, I just simulated the communication with a null modem emulator, which doesn't behave exactly the same.

Please leave a comment if it now works or not.

**Comment by Eric-11** [comment]
Thanks for the quick response. This fixed the "form format" error and it was able to decrypt and write it. I however wasn't able to load and unload the cartridge to verify the write was accepted properly. But there were no errors and the decryption looked correct.

Please close this issue and assume it's fixed. If I run into any other problems I'll let you know. Thanks again!
